parameters:
    enqueue_events_queue: 'symfony_events'

services:
    # should be defined by the extension
    # enqueue.events.context:

    enqueue.events.registry:
        class: 'Enqueue\AsyncEventDispatcher\ContainerAwareRegistry'
        public: false
        arguments: [[], [], '@service_container']

    enqueue.events.async_listener:
        class: 'Enqueue\AsyncEventDispatcher\AsyncListener'
        public: public
        arguments: ['@enqueue.events.context', '@enqueue.events.registry', '%enqueue_events_queue%']


    enqueue.events.event_dispatcher:
        class: 'Enqueue\AsyncEventDispatcher\AsyncEventDispatcher'
        public: public
        arguments:
            - '@event_dispatcher'
            - '@enqueue.events.async_listener'

    enqueue.events.php_serializer_event_transformer:
        class: 'Enqueue\AsyncEventDispatcher\PhpSerializerEventTransformer'
        public: public
        arguments:
            - '@enqueue.events.context'
        tags:
            - {name: 'enqueue.event_transformer', eventName: '/.*/', transformerName: 'php_serializer', default: true }
